config/routes.rb
MugsApp::Application.routes.draw do
  

  
  resources :jails, :only => [:index, :show] do 
    resources :bookings
  end
  resources :orders
  
  match '/jails/:jail_id/bookings/:id/remove' => 'orders#new', :as => :remove_booking
  match '/orders/:id/confirm' => 'orders#confirm', :as => :confirm_purchase
  
  root :to => 'jails#index'
end

app/models/bookings.rb
class Bookings < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :mugshot, :inmate_name, :booking_no, :jail_id, :bond
 	belongs_to :jail
 	has_many :charges
 	
  mount_uploader :mugshot, MugshotUploader
 	
 	validates :inmate_name, :presence => true
 	validates :booking_no, :presence => true
 	#validates :bond, :numericality => {:greater_than_or_equal_to => 0}
 	
end

app/models/charges.rb
class Charges < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :charge_name, :booking_id
  validates :charge_name, :presence => true
end

app/models/download_task.rb
class DownloadTask < ActiveRecord::Base
  attr_accessible :booking_id, :is_downloaded, :is_processed, :jail_id, :local_filename, :remote_filename
end

app/models/jails.rb
class Jails < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :short_name, :full_name
  
  has_many :bookings
  
  validates :short_name, :presence => true, :uniqueness => true
  validates :full_name, :presence => true, :uniqueness => true
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :booking_id, :email, :stripe_card_token, :inmate_name
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_filter :get_jail
  
  def show
    @booking = Bookings.find_by_id(params[:id])
    @charges = Charges.find_all_by_booking_id(params[:id])
  end
  
  private
  
  def get_jail
    @jail = Jails.find(params[:jail_id])
  end
end

app/controllers/jails_controller.rb
class JailsController < ApplicationController

	def index
		@jails = Jails.all
	end
	
  def show
      @jail = Jails.find(params[:id])
      @bookings = Bookings.where(
        'jail_id = ? AND is_purchased = ? AND is_downloaded = ?',
         params[:id], false, true).order("booking_datetime DESC").page(params[:page]).per(10)
  end
	

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new
    @order.booking_id = params[:id]
    @booking = Bookings.find_by_id(params[:id])
    @order.inmate_name = @booking.inmate_name
    @order.booking_id = @booking.id
    @order.remote_ip = request.remote_ip
    if @booking.nil?
      redirect_to root_url, :notice => "Booking not found!"
    end
    
    # render new.html.erb
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])
    
    if @order.save
      render 'confirm'
    end
    
  end
  
  # confirm purchase
  def confirm
    @order = Order.find(params[:id])
    @order.transaction do
      begin
        charge = Stripe::Charge.create(
          :amount => 10000,
          :currency => 'usd',
          :card => @order.stripe_card_token,
          :description => "#{@order.booking_id} - #{@order.inmate_name} - #{@order.email}"
        )
      rescue Stripe::InvalidRequestError => e
        logger.error "Stripe error on charge: #{e.message}"
        errors.add :base, "There was a problem: #{e.message}"
      rescue Stripe::CardError => e
        logger.error "Stripe error on charge: #{e.message}"
        redirect_to remove_booking_url(:id => @order.booking_id)
      end
      @order.is_complete = true
      @booking = Bookings.find(@order.booking_id)
      @booking.is_purchased = true

      @order.save
      @booking.save

      render 'thank_you'  
    end
    
  end
  
  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/jails_helper.rb
module JailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/bookings/show.html.erb
<% if @booking.is_purchased %>
  <h1>The requested resource is unavailable</h1> 
<% else %>

  <h1><%= @booking.inmate_name %></h1>
  <h2>Bond: <%= @booking.bond %></h2>
  <h2>Booking time: <%= @booking.booking_datetime.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%Y at %I:%M%p %Z   ")
 %></h2>
  <%= image_tag @booking.mugshot_url.to_s %>
  <% @charges.each do |c| %>
    <p>
      <%= c.charge_name %>
    </p>
  <% end %>

  <%= link_to "Remove mugshot", remove_booking_url(:id => @booking.id) %>
  
<% end %>  

app/views/jails/index.html.erb
<h2>Select a jail</h2>
<% @jails.each do |jail| %>
	<%= link_to jail.full_name, jail_path(jail) %>
<% end %>

app/views/jails/show.html.erb
<%= @jail.full_name %><br />
<%= paginate @bookings %>

  <% @bookings.each do |b| %>
    <div class="mugshot_box" > 
      <%= link_to image_tag(b.mugshot_url(:thumb).to_s, :alt => b.inmate_name),jail_booking_path(@jail,b) %><br />
      <div class="inmate_name">
        <%= b.inmate_name %>
      </div>
    </div>
  <% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html> 
<head>
<title>MugsApp</title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
<%= csrf_meta_tags %>
<%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="booking_info">
    <p>
      <%= @booking.inmate_name %>
    
      <%= @booking.id %>
    </p>
  </div>
  <%= f.hidden_field :booking_id %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :card_type %><br />
    <%= f.select :card_type, options_for_select([["Visa", 'visa'], ["Mastercard", "mc"], "American Express", "amex"]) %>
  </div>
  <div class="field">
    <%= f.label :card_expires_on %><br />
    <%= f.date_select :card_expires_on %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/confirm.html.erb
<h3>Please confirm your purchase.</h3>
<p>
  You are removing mugshot for  
  <%= @order.inmate_name %> for $100. 
  To confirm purchase, click "Confirm Purchase"
</p>
  
<%= form_for @order, :url => confirm_purchase_url(@order) do |f| %>
  <%= f.submit "Confirm Purchase" %> 
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Booking</th>
    <th>Inmate Name</th>
    <th>Email</th>
    <th>Stripe token</th>
    <th>Is complete?</th>
    <th>Remote ip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.booking_id %></td>
    <td><%= order.inmate_name %> </td>
    <td><%= order.email %></td>
    <td><%= order.stripe_card_token %></td>
    <td><%= order.is_complete %></td>
    <td><%= order.remote_ip %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<%= form_for @order do |f| %>
  <%= f.hidden_field :stripe_card_token %>
  <%= f.hidden_field :booking_id %>
  <%= f.hidden_field :inmate_name %>
  
 
  <h3>Purchasing removal of booking <%= @order.booking_id %> for $100</h3>
  <div class="field">
    <%= f.label :email, "Please enter your email address (for email confirmation of order)" %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= label_tag :card_number, "Credit Card Number" %>
    <%= text_field_tag :card_number, nil, name: nil %>
  </div>
  <div class="field">
    <%= label_tag :card_code, "CCV Code" %>
    <%= text_field_tag :card_code, nil, name: nil %>
  </div>
  <div class="field">
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, {add_month_numbers_true: true}, {name: nil, id: "card_month"} %>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
  </div>
  <div id="stripe_errors">
    <noscript>Javascript is not enabled in your webbrowser. Please enable Javascript and try again</noscript>
  </div>
  <div class="actions"><%= f.submit "Purchase product" %></div>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Booking:</b>
  <%= @order.booking_id %>
</p>

<p>
  <b>First name:</b>
  <%= @order.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @order.last_name %>
</p>

<p>
  <b>Card type:</b>
  <%= @order.card_type %>
</p>

<p>
  <b>Card expires on:</b>
  <%= @order.card_expires_on %>
</p>

<p>
  <b>Remote ip:</b>
  <%= @order.remote_ip %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/thank_you.html.erb
<h2>Thank you for your purchase</h2>
<p>
  TODO: Add more info
</p>
<%= link_to "Return to Home Page", root_url %>